### PR TITLE
CommonJS support

### PR DESCRIPTION
**Pull request by fredriks**

### CODE REVIEW

**Comment by DanielaValero** [comment]
Hello,

Is there a plan to have this merged and published any time soon? Would be good to be able to have commonJS support

**Comment by mtrias** [comment]
Sure!... i'm glad to merge. Can someone please fix the conflicts first?

**Comment by TheSharpieOne** [comment]
`require('angular-recaptcha');` and `import 'angular-recaptcha';` currently work just fine.
All this PR does is give you the ability to set variables with the module name so you can give it to angular instead of having to use a string.

**Comment by fredriks** [comment]
Conflicts resolved!

**Comment by mtrias** [comment]
Thanks @fredriks!

**Comment by DanielaValero** [comment]
Hi! did not see the notifications about the open tasks for this. Otherwise also would have helped. I am glad that you guys got it merged! Thanks!

**Comment by Lars-Weber** [comment]
Hey @mtrias ,

thanks so much for dealing with this so quickly!

Could you publish the 4.0.4 release on npm?

**Comment by mtrias** [comment]
Doh... always forget this. We need a script :P

It's done now!

**Comment by Lars-Weber** [comment]
np! :-)

Thanks so much!

**Pull request merged**
