### PR TITLE
Fix broken angular translate attr for meta tags in template

### PR DESCRIPTION
**Pull request by mmsqe**

### CODE REVIEW

**Comment by knocte** [comment]
@mtrias can you review please?

**Comment by mtrias** [comment]
What am I reviewing here? Where's the issue that this PR is fixing? I tried the original code and worked fine for me.

**Comment by mmsqe** [comment]
since when we use translate-attr-content from angular for meta content, meta content becomes empty when using jQuery append, while we can avoid this angular digest issue when using native appendChild.
current_result
expected_result

**Comment by mtrias** [comment]
Gotcha, thanks for clarifying. 

Please remove the files under `/release`. We'll generate the release files as part of the release process.

**Comment by mtrias** [comment]
@knocte you also are experiencing this bug? If yes, can you confirm this PR fixes it?

**Comment by mtrias** [comment]
Thanks @mmsqe !

**Pull request merged**
