### PR TITLE
Removed jQuery dependency

### LINKED ISSUE #178: angular-recaptcha requires jQuery
Errors occur when Angular is used without jQuery (then Angular uses jqLite internally), e.g. at lines:
```js
// Generate link on demand
var script = $document.get(0).createElement('script');
script.async = true;
script.defer = true;
script.src = 'https://www.google.com/recaptcha/api.js?onload='+provider.onLoadFunctionName+'&render=explicit';
$document.get(0).body.appendChild(script);
```

as `$document` does not have method `get()`.

Introduced in 82d33e6adabdd81a0341b6e68866f28b0f760522

Fix provided in #181

### PR DESCRIPTION
**Pull request by mrwogu**
Resolves #178 & #179

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Lots of unrelated and unneeded formatting. Also the release files usually shouldn't be in the PR.

**Comment by mrwogu** [comment]
@TheSharpieOne, now should be fine.

**Comment by iambrosi** [comment]
Thanks @mrwogu !!

**Comment by TheSharpieOne** [comment]
This need to be released.

**Comment by iambrosi** [comment]
Done!

**Comment by TheSharpieOne** [comment]
@iambrosi looks like the release directory was not updated.

**Comment by iambrosi** [comment]
Sorry, now should be fixed

**Pull request merged**
