### PR TITLE
Dynamic language binding

### PR DESCRIPTION
**Pull request by geo242**
I needed this functionality in an app I am working on, so I thought I would contribute the change if you want it.

I have added support to dynamically bind a language parameter. This involves reloading the reCaptcha script from google, so there is no longer a need to include the reCaptcha script tag. I also updated the documentation accordingly. Let me know if this is too big of a change.

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
I see language is defined on the directive, what happens if you have multiple directives with different languages on the same page at the same time?
It also appears that the recaptcha script will be injected each time a new directive is created which seems wasteful and possibly even problematic for any time more than one recaptcha is loaded (as the recaptcha script assumes checks some globals and overrides others which would have been set by previous, possibly still active recaptcha widgets.

**Comment by geo242** [comment]
Good point about the language attribute. I will change that to something like recaptcha-language.

The script has to be injected every time because of how Google handles languages for reCaptcha. I agree it's not ideal. I have tested it pretty extensively and haven't noticed any issues.

**Comment by mtrias** [comment]
I may be wrong, but my initial impression here, is that it requires too much complexity for a feature that IMO not many people need. Actually, I wonder why would you need to change the language dynamically?

Regarding the PR itself, i see two issues with it:
1. It's lacking tests
2. Is modifying the release files instead of the source files.

**Comment by geo242** [comment]
@mtrias 
1. The project doesn't contain test currently, at least not in the master branch.
2. If you scroll down further, you can see that the source files were modified. The release files were only modified due to the grunt build process.

The reason I need to change the language on the fly is because the app I am building will be used on a kiosk computer, so the app has to be able to let the user choose their language. The OS or browser language cannot be used as a basis.

**Comment by mtrias** [comment]
Thanks for the clarification @geo242 

Maybe you have an outdated master? I'm pretty sure there are [tests](https://travis-ci.org/VividCortex/angular-recaptcha/builds/122666573) in the project.

**Comment by geo242** [comment]
@mtrias that may be. I will update and add tests

**Comment by TheSharpieOne** [comment]
I'd suggest moving setting the language from the directive to the provider/service as the language is probably of the site and not the individual directives.
Also, maybe using the language of the webpage by default (not the OS or browser language, but the `lang` attribute on the `html` tag) if it is there (just to help others even if the kiosk doesn't use it (really, it should, as the `lang` should be set to the language that is displayed on the page).

**Comment by geo242** [comment]
@TheSharpieOne good points. I will make those adjustments.

**Comment by rhclayto** [comment]
Hi,

This is great, i was working on a solution for this as well & was about 90% there, but now I'm investigating this.

The first time I load a page it sets the captcha to the correct language based on the model value that this new language attribute is tied to. However, the first time I change the language, I get the error 'ReCAPTCHA has already been rendered in this element' & the captcha is not rendered. For every subsequent language change the captcha *is* rendered, but it is rendered with the value of the language that preceded it. So for instance, after that initial error, i change the language from Arabic to German. Now the language of the site has changed to German but the captcha is rendered as Arabic. No errors are thrown. Now i change from German to Spanish. The language model is now Spanish, but the captcha renders in German, the previous model language.

In brief, the first model change causes an error, & every model change after that brings up a captcha with a language corresponding to the _previous_ model value.

**Comment by rhclayto** [comment]
I solved it by adding `delete $window.grecaptcha;` to the function `loadScript(url)` . Like so:

```javascript
function loadScript(url) {
delete $window.grecaptcha;
// remainder of function
}
```

It seems that when `return recaptcha = $window.grecaptcha;` is returned the $window.grecaptcha object is still the object created with the previous script. Deleting the object before calling the script allows `return recaptcha = $window.grecaptcha;` to use the $window.grecaptcha from the new script, not the previous one.

I added the change to the unminified release script from my fork of  geo242's fork: https://github.com/rhclayto/angular-recaptcha/blob/language-binding/release/angular-recaptcha.js

**Comment by molerat619** [comment]
Hey guys, good job. But how can I use this now?

**Comment by xarv** [comment]
are you guys planning to merge this ?

**Comment by iambrosi** [comment]
@xarv There are some points that need to be addressed before merging this. I'm referring to [this comment](#issuecomment-215753691), and [this other comment](#issuecomment-215767332). Also, the PR has conflicts that need to be resolved.

**Comment by molerat619** [comment]
Anything new here? Still looking for a working solution

**Comment by mtrias** [comment]
This PR needs more work in order to be merged. If you want to use the feature you can always use the PR's author fork.

**Comment by TheSharpieOne** [comment]
superseded by #170

**Comment by TheSharpieOne** [comment]
This is obsolete and should be closed.

**Pull request closed without merging**
